name: "semantic pull request"
description: "Validate Title and Body of Pull Request for conventional commit"
branding:
  icon: "git-commit"
  color: "green"
inputs:
  valid-scopes:
    description: "Defines list of valid scopes. By default any scope entry is valid."
    required: false
    default: '' #comma separated list of scopes i.e tab, button
  scope-required:
    description: "Defines if scope is required in commit message. By default scope is optional and not required."
    required: false
    default: false

runs:
  using: "node12"
  main: "./dist/index.js"
  